<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    /* SETTINGS */
    'SHOP_MODULE_GROUP_STRIPE_GENERAL'                  => 'Grundkonfiguration',
    'SHOP_MODULE_sStripeMode'                           => 'Modus',
    'SHOP_MODULE_sStripeMode_live'                      => 'Live',
    'SHOP_MODULE_sStripeMode_test'                      => 'Test',
    'SHOP_MODULE_sStripeTestToken'                      => 'Test API Key',
    'SHOP_MODULE_sStripeTestPk'                         => 'Test API Publishable Key',
    'SHOP_MODULE_sStripeLiveToken'                      => 'Live API Key',
    'SHOP_MODULE_sStripeLivePk'                         => 'Live API Publishable Key',
    'SHOP_MODULE_sStripeTestKey'                        => 'Test API Private Key',
    'SHOP_MODULE_sStripeLiveKey'                        => 'Live API Private  Key',
    'SHOP_MODULE_blStripeLogTransactionInfo'            => 'Ergebnisse von Transaktions-Verarbeitung loggen',
    'SHOP_MODULE_blStripeRemoveDeactivatedMethods'      => 'Deaktivierte Zahlarten entfernen',
    'SHOP_MODULE_blStripeRemoveByBillingCountry'        => 'F&uuml;r Rechnungsland nicht unterst&uuml;tzte Zahlarten entfernen',
    'SHOP_MODULE_blStripeRemoveByBasketCurrency'        => 'F&uuml;r W&auml;hrung nicht unterst&uuml;tzte Zahlarten entfernen',
    'SHOP_MODULE_GROUP_STRIPE_STATUS_MAPPING'           => 'Status Mapping',
    'SHOP_MODULE_sStripeStatusPending'                  => 'Status Ausstehend',
    'SHOP_MODULE_sStripeStatusProcessing'               => 'Status in Bearbeitung',
    'SHOP_MODULE_sStripeStatusCancelled'                => 'Status Storniert',
    'SHOP_MODULE_GROUP_STRIPE_CRONJOBS'                 => 'Cronjobs',
    'SHOP_MODULE_sStripeCronFinishOrdersActive'         => 'Cronjob "Abschluss von bezahlten aber nicht vollendeten Bestellungen" aktiv',
    'SHOP_MODULE_sStripeCronSecondChanceActive'         => 'Cronjob "Versand einer Zahlungs-Erinnerungs-Email" aktiv',
    'SHOP_MODULE_iStripeCronSecondChanceTimeDiff'       => 'Zeitfenster nach dem Zahlungs-Erinnerungs-Email versendet wird',
    'SHOP_MODULE_sStripeCronOrderShipmentActive'        => 'Cronjob "&Uuml;bermittlung von Versandstatus an Stripe" aktiv',
    'SHOP_MODULE_sStripeCronSecureKey'                  => 'Cronjob Sicherheits-Schlüssel',
    'SHOP_MODULE_GROUP_STRIPE_WEBHOOKS'                 => 'Webhooks',
    'SHOP_MODULE_sStripeWebhookEndpoint'                => 'Webhook Endpoint',

    'HELP_SHOP_MODULE_sStripeTestKey'                   => 'Geben Sie Ihren persönlichen privaten TEST-API-Schlüssel ein, der zum Einrichten des Webhook-Endpunkts verwendet wird.',
    'HELP_SHOP_MODULE_sStripeLiveKey'                   => 'Geben Sie Ihren persönlichen privaten LIVE-API-Schlüssel ein, der zum Einrichten des Webhook-Endpunkts verwendet wird.',
    'HELP_SHOP_MODULE_blStripeLogTransactionInfo'       => 'Log-Datei zu finden unter SHOPROOT/log/StripeTransactions.log',
    'HELP_SHOP_MODULE_blStripeRemoveDeactivatedMethods' => 'Entfernt in der Zahlart-Auswahl im Frontend die Zahlarten, die im Stripe Dashboard nicht aktiviert wurden und somit zu einem Fehler f&uuml;hren w&uuml;rden.',
    'HELP_SHOP_MODULE_blStripeRemoveByBillingCountry'   => 'Entfernt in der Zahlart-Auswahl im Frontend die Zahlarten, die f&uuml;r das vom Kunden angegebene Rechnungsland nicht unterst&uuml;tzt sind und somit zu einem Fehler f&uuml;hren w&uuml;rden.',
    'HELP_SHOP_MODULE_blStripeRemoveByBasketCurrency'   => 'Entfernt in der Zahlart-Auswahl im Frontend die Zahlarten, die f&uuml;r das vom Warenkorb angegebene W&auml;rung nicht unterst&uuml;tzt sind und somit zu einem Fehler f&uuml;hren w&uuml;rden.',
    'HELP_SHOP_MODULE_sStripeStatusPending'             => 'Legen Sie den Bestell-Status fest, bevor der Kunde zum Zahlungs-Gateway umgeleitet wird',
    'HELP_SHOP_MODULE_sStripeStatusProcessing'          => 'Legen Sie den Bestell-Status für Abgeschlossene Zahlungen fest',
    'HELP_SHOP_MODULE_sStripeStatusCancelled'           => 'Legen Sie den Bestell-Status für stornierte Bestellungen fest',
    'HELP_SHOP_MODULE_sStripeCronFinishOrdersActive'    => 'Dieser Cronjob hat zur Aufgabe Bestellungen abzuschließen, bei denen der Kunde erfolgreich bezahlt hat, aber scheinbar nicht wieder in den Shop zurückgekehrt ist für den Abschluss des Bestellvorgangs. Der Cronjob finalisiert nur Bestellungen aus den letzten 24 Stunden, um keine Bestellungen zu ver&auml;ndern die wahrscheinlich schon manuell bearbeitet wurden.<br><br>Damit dieser Cronjob arbeitet, m&uuml;ssen Sie zus&auml;tzlich zu dieser Checkbox noch sicherstellen dass der Stripe Cronjob eingerichtet ist. Mehr dazu erfahren Sie in der README.md Datei des Moduls.',
    'HELP_SHOP_MODULE_sStripeCronSecondChanceActive'    => 'Damit dieser Cronjob arbeitet, m&uuml;ssen Sie zus&auml;tzlich zu dieser Checkbox noch sicherstellen dass der Stripe Cronjob eingerichtet ist. Mehr dazu erfahren Sie in der README.md Datei des Moduls.',
    'HELP_SHOP_MODULE_sStripeCronOrderShipmentActive'   => 'Dieser Cronjob ist nur notwendig, wenn der Versandstatus in Ihrem Shop &uuml;ber ein externes System gesetzt wird und NICHT &uuml;ber den "Jetzt versenden" Button im Oxid-Admin. Damit dieser Cronjob arbeitet, m&uuml;ssen Sie zus&auml;tzlich zu dieser Checkbox noch sicherstellen dass der Stripe Cronjob eingerichtet ist. Mehr dazu erfahren Sie in der README.md Datei des Moduls.',
    'HELP_SHOP_MODULE_sStripeCronSecureKey'             => 'Diese Option ben&ouml;tigen Sie nur, wenn Sie den Cronjob per URL aufrufen m&uuml;ssen anstelle von dem Aufruf über die php cli. Konfigurieren Sie hier einen Sicherheitsschlüssel, den Sie über den GET-Parameter "secureKey" an den Aufruf des Cronjobs anf&uuml;gen. Bsp.: https://YOUR-SHOP-URL-HERE/modules/fc/stripe/cron.php?secureKey=YOUR-SECURE-KEY',

    'STRIPE_YES'                                        => 'Ja',
    'STRIPE_NO'                                         => 'Nein',
    'STRIPE_DAY'                                        => 'Tag',
    'STRIPE_DAYS'                                       => 'Tage',
    'STRIPE_IS_STRIPE'                                  => 'Dies ist eine Stripe Zahlungsart',
    'STRIPE_IS_METHOD_ACTIVATED'                        => 'Diese Zahlungsart ist in Ihrem Stripe Account nicht aktiviert!',
    'STRIPE_TOKEN_NOT_CONFIGURED'                       => 'Ihr Stripe-Token wurde noch nicht konfiguriert!',
    'STRIPE_KEY_NOT_CONFIGURED'                         => 'Ihr privater Stripe-Schl&uuml;ssel wurde noch nicht konfiguriert! Bitte konfigurieren Sie es in der Basiskonfiguration.',
    'STRIPE_DUE_DATE'                                   => 'F&auml;lligkeitstage',
    'STRIPE_BANKTRANSFER_PENDING'                       => 'Status Ausstehend',
    'STRIPE_ORDER_REFUND'                               => 'Stripe',
    'STRIPE_REFUND_SUCCESSFUL'                          => 'R&uuml;ckerstattung war erfolgreich.',
    'STRIPE_NO_STRIPE_PAYMENT'                          => 'Diese Bestellung wurde nicht mit Stripe bezahlt.',
    'STRIPE_REFUND_QUANTITY'                            => 'Erstattungsmenge',
    'STRIPE_REFUND_AMOUNT'                              => 'Erstattungsbetrag',
    'STRIPE_TYPE_SELECT_LABEL'                          => 'Erstattung durchf&uuml;hren &uuml;ber',
    'STRIPE_QUANTITY'                                   => 'Menge',
    'STRIPE_NOTICE'                                     => 'Hinweis',
    'STRIPE_AMOUNT'                                     => 'Betrag',
    'STRIPE_HEADER_ORDERED'                             => 'Bezahlt',
    'STRIPE_HEADER_REFUNDED'                            => 'Erstattet',
    'STRIPE_HEADER_SINGLE_PRICE'                        => 'Einzelpreis',
    'STRIPE_SHIPPINGCOST'                               => "Versandkosten",
    'STRIPE_PAYMENTTYPESURCHARGE'                       => "Zahlungsart-Aufschlag",
    'STRIPE_WRAPPING'                                   => "Geschenkverpackung",
    'STRIPE_GIFTCARD'                                   => "Grußkarte",
    'STRIPE_VOUCHER'                                    => 'Gutschein',
    'STRIPE_DISCOUNT'                                   => 'Rabatt',
    'STRIPE_REFUND_SUBMIT'                              => 'Erstattung durchf&uuml;hren',
    'STRIPE_FULL_REFUND'                                => 'Vollst&auml;ndige R&uuml;ckerstattung',
    'STRIPE_FULL_REFUND_TEXT'                           => 'Vollst&auml;ndige Erstattung durchf&uuml;hren &uuml;ber Betrag von',
    'STRIPE_FULL_REFUND_NOT_AVAILABLE'                  => 'Eine Vollst&auml;ndige R&uuml;ckerstattung ist f&uuml;r diese Bestellung nicht mehr verf&uuml;gbar, da Sie bereits Einzelpositionen zur&uuml;ckerstattet haben.',
    'STRIPE_REFUND_DESCRIPTION'                         => 'Erstattungs-Hinweis',
    'STRIPE_REFUND_DESCRIPTION_PLACEHOLDER'             => 'Optional - Max 140 Zeichen',
    'STRIPE_ORDER_NOT_REFUNDABLE'                       => 'Diese Bestellung wurde bereits vollst&auml;ndig erstattet.',
    'STRIPE_REFUND_REMAINING'                           => 'Verbliebene Summe erstatten',
    'STRIPE_APPLE_PAY_BUTTON_ONLY_LIVE_MODE'            => 'Hinweis: Bezahlung mit Apple Pay Button ist nur im Live-Modus m&ouml;glich',
    'STRIPE_APIKEY_CONNECTED'                           => 'Verbindung erfolgreich',
    'STRIPE_APIKEY_DISCONNECTED'                        => 'Verbindung nicht erfolgreich',
    'STRIPE_DEACTIVATED'                                => 'Deaktiviert',
    'STRIPE_CONNECTION_DATA'                            => 'Abruf der Verbindungsdaten &uuml;ber:',
    'STRIPE_ORDER_PAYMENT_URL'                          => 'Link zum Abschluss der Zahlung',
    'STRIPE_SEND_SECOND_CHANCE_MAIL'                    => 'Second Chance Email versenden',
    'STRIPE_SECOND_CHANCE_MAIL_ALREADY_SENT'            => 'Die Email wurde bereits versendet.',
    'STRIPE_SUBSEQUENT_ORDER_COMPLETION'                => 'Nachtr&auml;glicher Bestellabschluss',
    'STRIPE_PAYMENT_DESCRIPTION'                        => 'Zahlungsbezeichnung',
    'STRIPE_PAYMENT_DESCRIPTION_HELP'                   => 'Dies wird auf dem Kontoauszug des Kunden angezeigt soweit m&ouml;glich.<br><br>Sie k&ouml;nnen die folgenden Parameter benutzen:<br>{orderId}<br>{orderNumber}<br>{storeName}<br>{customer.firstname}<br>{customer.lastname}<br>{customer.company}',
    'STRIPE_MODULE_VERSION_OUTDATED'                    => 'Achtung! Die aktuellste Modulversion ist',
    'STRIPE_PAYMENT_LIMITATION'                         => 'Stripe Beschr&auml;nkung',
    'STRIPE_PAYMENT_LIMITATION_FROM'                    => 'Von',
    'STRIPE_PAYMENT_LIMITATION_TO'                      => 'bis',
    'STRIPE_PAYMENT_LIMITATION_UNLIMITED'               => 'unbegrenzt',
    'STRIPE_PAYMENT_DETAILS'                            => 'Zahlungsdetails',
    'STRIPE_PAYMENT_TYPE'                               => 'Zahlart',
    'STRIPE_TRANSACTION_ID'                             => 'Stripe Transaktions ID',
    'STRIPE_EXTERNAL_TRANSACTION_ID'                    => 'Externe Transaktions ID',
    'STRIPE_ORDER_EXTRA_INFO'                           => 'Zus&auml;tzliche Informationen',
    'STRIPE_CONNECT_SUCCESS'                            => 'Stripe-Onboarding erfolgreich.',
    'STRIPE_CONNECT_ERROR'                              => 'W&auml;hrend des Stripe-Onboardings ist ein Fehler aufgetreten.',
    'STRIPE_BTN_TO_ADMIN'                               => 'Zum Admin-Bereich',
    'STRIPE_CONFIG_WEBHOOK_CREATE'                      => 'Webhooks erstellen',
    'STRIPE_CONFIG_WEBHOOK_FORCE'                       => 'Aktualisierung der Webhooks erzwingen',
    'STRIPE_WEBHOOK_SET'                                => 'Webhook-Endpunkt ist konfiguriert.',
    'STRIPE_WEBHOOK_MISSING'                            => 'Webhook-Endpunkt fehlt oder ist ung&uuml;ltig.',
    'STRIPE_WEBHOOK_CREATE_ERROR'                       => 'Der Webhook-Endpunkt konnte nicht erstellt werden.',
    'STRIPE_WEBHOOK_CREATE_ERROR_DELETE_FAILED'         => 'Der Webhook-Endpunkt konnte nicht erstellt werden. Das L&ouml;schen des vorhandenen WH-Endpunkts ist fehlgeschlagen.',
    'STRIPE_REFUND_REASON'                              => 'R&uuml;ckerstattungsgrund (optional)',
    'STRIPE_PLEASE_SELECT'                              => '-- Bitte w&auml;hlen Sie --',
    'STRIPE_REFUND_DUPLICATE'                           => 'Duplikat',
    'STRIPE_REFUND_CUSTOMER'                            => 'Vom Kunden angefordert',
    'STRIPE_REFUND_FRAUD'                               => 'Betrug',
);
