<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    /* SETTINGS */
    'SHOP_MODULE_GROUP_STRIPE_GENERAL'                  => 'Grundkonfiguration',
    'SHOP_MODULE_sStripeMode'                           => 'Modus',
    'SHOP_MODULE_sStripeMode_live'                      => 'Live',
    'SHOP_MODULE_sStripeMode_test'                      => 'Test',
    'SHOP_MODULE_sStripeTestToken'                      => 'Test API Key',
    'SHOP_MODULE_sStripeTestPk'                         => 'Test API Publishable Key',
    'SHOP_MODULE_sStripeLiveToken'                      => 'Live API Key',
    'SHOP_MODULE_sStripeLivePk'                         => 'Live API Publishable Key',
    'SHOP_MODULE_sStripeTestKey'                        => 'Test API Private Key',
    'SHOP_MODULE_sStripeLiveKey'                        => 'Live API Private  Key',
    'SHOP_MODULE_blStripeLogTransactionInfo'            => 'Ergebnisse von Transaktions-Verarbeitung loggen',
    'SHOP_MODULE_blStripeRemoveDeactivatedMethods'      => 'Deaktivierte Zahlarten entfernen',
    'SHOP_MODULE_blStripeRemoveByBillingCountry'        => 'Für Rechnungsland nicht unterstützte Zahlarten entfernen',
    'SHOP_MODULE_blStripeRemoveByBasketCurrency'        => 'Für Währung nicht unterstützte Zahlarten entfernen',
    'SHOP_MODULE_GROUP_STRIPE_STATUS_MAPPING'           => 'Status Mapping',
    'SHOP_MODULE_sStripeStatusPending'                  => 'Status Ausstehend',
    'SHOP_MODULE_sStripeStatusProcessing'               => 'Status in Bearbeitung',
    'SHOP_MODULE_sStripeStatusCancelled'                => 'Status Storniert',
    'SHOP_MODULE_GROUP_STRIPE_CRONJOBS'                 => 'Cronjobs',
    'SHOP_MODULE_sStripeCronFinishOrdersActive'         => 'Cronjob "Abschluss von bezahlten aber nicht vollendeten Bestellungen" aktiv',
    'SHOP_MODULE_sStripeCronSecondChanceActive'         => 'Cronjob "Versand einer Zahlungs-Erinnerungs-Email" aktiv',
    'SHOP_MODULE_iStripeCronSecondChanceTimeDiff'       => 'Zeitfenster nach dem Zahlungs-Erinnerungs-Email versendet wird',
    'SHOP_MODULE_sStripeCronOrderShipmentActive'        => 'Cronjob "Übermittlung von Versandstatus an Stripe" aktiv',
    'SHOP_MODULE_sStripeCronSecureKey'                  => 'Cronjob Sicherheits-Schlüssel',
    'SHOP_MODULE_GROUP_STRIPE_WEBHOOKS'                 => 'Webhooks',
    'SHOP_MODULE_sStripeWebhookEndpoint'                => 'Webhook Endpoint',
    'SHOP_MODULE_blStripeProvideCustomerEmailAddress'   => 'Kunden-E-Mail-Adresse an Stripe senden',

    'HELP_SHOP_MODULE_sStripeTestKey'                   => 'Geben Sie Ihren persönlichen privaten TEST-API-Schlüssel ein, der zum Einrichten des Webhook-Endpunkts verwendet wird.',
    'HELP_SHOP_MODULE_sStripeLiveKey'                   => 'Geben Sie Ihren persönlichen privaten LIVE-API-Schlüssel ein, der zum Einrichten des Webhook-Endpunkts verwendet wird.',
    'HELP_SHOP_MODULE_blStripeLogTransactionInfo'       => 'Log-Datei zu finden unter SHOPROOT/log/StripeTransactions.log',
    'HELP_SHOP_MODULE_blStripeRemoveDeactivatedMethods' => 'Entfernt in der Zahlart-Auswahl im Frontend die Zahlarten, die im Stripe Dashboard nicht aktiviert wurden und somit zu einem Fehler führen würden.',
    'HELP_SHOP_MODULE_blStripeRemoveByBillingCountry'   => 'Entfernt in der Zahlart-Auswahl im Frontend die Zahlarten, die für das vom Kunden angegebene Rechnungsland nicht unterstützt sind und somit zu einem Fehler führen würden.',
    'HELP_SHOP_MODULE_blStripeRemoveByBasketCurrency'   => 'Entfernt in der Zahlart-Auswahl im Frontend die Zahlarten, die für das vom Warenkorb angegebene Wärung nicht unterstützt sind und somit zu einem Fehler führen würden.',
    'HELP_SHOP_MODULE_sStripeStatusPending'             => 'Legen Sie den Bestell-Status fest, bevor der Kunde zum Zahlungs-Gateway umgeleitet wird',
    'HELP_SHOP_MODULE_sStripeStatusProcessing'          => 'Legen Sie den Bestell-Status für Abgeschlossene Zahlungen fest',
    'HELP_SHOP_MODULE_sStripeStatusCancelled'           => 'Legen Sie den Bestell-Status für stornierte Bestellungen fest',
    'HELP_SHOP_MODULE_sStripeCronFinishOrdersActive'    => 'Dieser Cronjob hat zur Aufgabe Bestellungen abzuschließen, bei denen der Kunde erfolgreich bezahlt hat, aber scheinbar nicht wieder in den Shop zurückgekehrt ist für den Abschluss des Bestellvorgangs. Der Cronjob finalisiert nur Bestellungen aus den letzten 24 Stunden, um keine Bestellungen zu verändern die wahrscheinlich schon manuell bearbeitet wurden.<br><br>Damit dieser Cronjob arbeitet, müssen Sie zusätzlich zu dieser Checkbox noch sicherstellen dass der Stripe Cronjob eingerichtet ist. Mehr dazu erfahren Sie in der README.md Datei des Moduls.',
    'HELP_SHOP_MODULE_sStripeCronSecondChanceActive'    => 'Damit dieser Cronjob arbeitet, müssen Sie zusätzlich zu dieser Checkbox noch sicherstellen dass der Stripe Cronjob eingerichtet ist. Mehr dazu erfahren Sie in der README.md Datei des Moduls.',
    'HELP_SHOP_MODULE_sStripeCronOrderShipmentActive'   => 'Dieser Cronjob ist nur notwendig, wenn der Versandstatus in Ihrem Shop über ein externes System gesetzt wird und NICHT über den "Jetzt versenden" Button im Oxid-Admin. Damit dieser Cronjob arbeitet, müssen Sie zusätzlich zu dieser Checkbox noch sicherstellen dass der Stripe Cronjob eingerichtet ist. Mehr dazu erfahren Sie in der README.md Datei des Moduls.',
    'HELP_SHOP_MODULE_sStripeCronSecureKey'             => 'Diese Option benötigen Sie nur, wenn Sie den Cronjob per URL aufrufen müssen anstelle von dem Aufruf über die php cli. Konfigurieren Sie hier einen Sicherheitsschlüssel, den Sie über den GET-Parameter "secureKey" an den Aufruf des Cronjobs anfügen. Bsp.: https://YOUR-SHOP-URL-HERE/modules/fc/stripe/cron.php?secureKey=YOUR-SECURE-KEY',
    'HELP_SHOP_MODULE_blStripeProvideCustomerEmailAddress' => 'Ist diese Option aktiviert so, wird bei einer Stripe-Bestellung die Kunden-EMailadresse ebenfalls übergeben. Das überschreibt die Standard-E-Mail-Einstellungen im Stripe-Account für diese Bestellung. Somit werden die Benachrichtigungen zu dieser Bestellung an die Kunden-EMail-Adresse gesendet, statt an die Stripe-Account-EMail-Adresse.',

    'STRIPE_YES'                                        => 'Ja',
    'STRIPE_NO'                                         => 'Nein',
    'STRIPE_DAY'                                        => 'Tag',
    'STRIPE_DAYS'                                       => 'Tage',
    'STRIPE_IS_STRIPE'                                  => 'Dies ist eine Stripe Zahlungsart',
    'STRIPE_IS_METHOD_ACTIVATED'                        => 'Diese Zahlungsart ist in Ihrem Stripe Account nicht aktiviert!',
    'STRIPE_TOKEN_NOT_CONFIGURED'                       => 'Ihr Stripe-Token wurde noch nicht konfiguriert!',
    'STRIPE_KEY_NOT_CONFIGURED'                         => 'Ihr privater Stripe-Schlüssel wurde noch nicht konfiguriert! Bitte konfigurieren Sie es in der Basiskonfiguration.',
    'STRIPE_DUE_DATE'                                   => 'Fälligkeitstage',
    'STRIPE_BANKTRANSFER_PENDING'                       => 'Status Ausstehend',
    'STRIPE_ORDER_REFUND'                               => 'Stripe',
    'STRIPE_REFUND_SUCCESSFUL'                          => 'Rückerstattung war erfolgreich.',
    'STRIPE_NO_STRIPE_PAYMENT'                          => 'Diese Bestellung wurde nicht mit Stripe bezahlt.',
    'STRIPE_REFUND_QUANTITY'                            => 'Erstattungsmenge',
    'STRIPE_REFUND_AMOUNT'                              => 'Erstattungsbetrag',
    'STRIPE_TYPE_SELECT_LABEL'                          => 'Erstattung durchführen über',
    'STRIPE_QUANTITY'                                   => 'Menge',
    'STRIPE_NOTICE'                                     => 'Hinweis',
    'STRIPE_AMOUNT'                                     => 'Betrag',
    'STRIPE_HEADER_ORDERED'                             => 'Bezahlt',
    'STRIPE_HEADER_REFUNDED'                            => 'Erstattet',
    'STRIPE_HEADER_SINGLE_PRICE'                        => 'Einzelpreis',
    'STRIPE_SHIPPINGCOST'                               => "Versandkosten",
    'STRIPE_PAYMENTTYPESURCHARGE'                       => "Zahlungsart-Aufschlag",
    'STRIPE_WRAPPING'                                   => "Geschenkverpackung",
    'STRIPE_GIFTCARD'                                   => "Grußkarte",
    'STRIPE_VOUCHER'                                    => 'Gutschein',
    'STRIPE_DISCOUNT'                                   => 'Rabatt',
    'STRIPE_REFUND_SUBMIT'                              => 'Erstattung durchführen',
    'STRIPE_FULL_REFUND'                                => 'Vollständige Rückerstattung',
    'STRIPE_FULL_REFUND_TEXT'                           => 'Vollständige Erstattung durchführen über Betrag von',
    'STRIPE_FULL_REFUND_NOT_AVAILABLE'                  => 'Eine Vollständige Rückerstattung ist für diese Bestellung nicht mehr verfügbar, da Sie bereits Einzelpositionen zurückerstattet haben.',
    'STRIPE_REFUND_DESCRIPTION'                         => 'Erstattungs-Hinweis',
    'STRIPE_REFUND_DESCRIPTION_PLACEHOLDER'             => 'Optional - Max 140 Zeichen',
    'STRIPE_ORDER_NOT_REFUNDABLE'                       => 'Diese Bestellung wurde bereits vollständig erstattet.',
    'STRIPE_REFUND_REMAINING'                           => 'Verbliebene Summe erstatten',
    'STRIPE_APPLE_PAY_BUTTON_ONLY_LIVE_MODE'            => 'Hinweis: Bezahlung mit Apple Pay Button ist nur im Live-Modus möglich',
    'STRIPE_APIKEY_CONNECTED'                           => 'Verbindung erfolgreich',
    'STRIPE_APIKEY_DISCONNECTED'                        => 'Verbindung nicht erfolgreich',
    'STRIPE_DEACTIVATED'                                => 'Deaktiviert',
    'STRIPE_CONNECTION_DATA'                            => 'Abruf der Verbindungsdaten über:',
    'STRIPE_ORDER_PAYMENT_URL'                          => 'Link zum Abschluss der Zahlung',
    'STRIPE_SEND_SECOND_CHANCE_MAIL'                    => 'Second Chance Email versenden',
    'STRIPE_SECOND_CHANCE_MAIL_ALREADY_SENT'            => 'Die Email wurde bereits versendet.',
    'STRIPE_SUBSEQUENT_ORDER_COMPLETION'                => 'Nachträglicher Bestellabschluss',
    'STRIPE_PAYMENT_DESCRIPTION'                        => 'Zahlungsbezeichnung',
    'STRIPE_PAYMENT_DESCRIPTION_HELP'                   => 'Dies wird auf dem Kontoauszug des Kunden angezeigt soweit möglich.<br><br>Sie können die folgenden Parameter benutzen:<br>{orderId}<br>{orderNumber}<br>{storeName}<br>{customer.firstname}<br>{customer.lastname}<br>{customer.company}',
    'STRIPE_MODULE_VERSION_OUTDATED'                    => 'Achtung! Die aktuellste Modulversion ist',
    'STRIPE_PAYMENT_LIMITATION'                         => 'Stripe Beschränkung',
    'STRIPE_PAYMENT_LIMITATION_FROM'                    => 'Von',
    'STRIPE_PAYMENT_LIMITATION_TO'                      => 'bis',
    'STRIPE_PAYMENT_LIMITATION_UNLIMITED'               => 'unbegrenzt',
    'STRIPE_PAYMENT_DETAILS'                            => 'Zahlungsdetails',
    'STRIPE_PAYMENT_TYPE'                               => 'Zahlart',
    'STRIPE_TRANSACTION_ID'                             => 'Stripe Transaktions ID',
    'STRIPE_EXTERNAL_TRANSACTION_ID'                    => 'Externe Transaktions ID',
    'STRIPE_ORDER_EXTRA_INFO'                           => 'Zusätzliche Informationen',
    'STRIPE_CONNECT_SUCCESS'                            => 'Stripe-Onboarding erfolgreich.',
    'STRIPE_CONNECT_ERROR'                              => 'Während des Stripe-Onboardings ist ein Fehler aufgetreten.',
    'STRIPE_BTN_TO_ADMIN'                               => 'Zum Admin-Bereich',
    'STRIPE_CONFIG_WEBHOOK_CREATE'                      => 'Webhooks erstellen',
    'STRIPE_CONFIG_WEBHOOK_FORCE'                       => 'Aktualisierung der Webhooks erzwingen',
    'STRIPE_WEBHOOK_SET'                                => 'Webhook-Endpunkt ist konfiguriert.',
    'STRIPE_WEBHOOK_MISSING'                            => 'Webhook-Endpunkt fehlt oder ist ungültig.',
    'STRIPE_WEBHOOK_CREATE_ERROR'                       => 'Der Webhook-Endpunkt konnte nicht erstellt werden.',
    'STRIPE_WEBHOOK_CREATE_ERROR_DELETE_FAILED'         => 'Der Webhook-Endpunkt konnte nicht erstellt werden. Das Löschen des vorhandenen WH-Endpunkts ist fehlgeschlagen.',
    'STRIPE_REFUND_REASON'                              => 'Rückerstattungsgrund (optional)',
    'STRIPE_PLEASE_SELECT'                              => '-- Bitte wählen Sie --',
    'STRIPE_REFUND_DUPLICATE'                           => 'Duplikat',
    'STRIPE_REFUND_CUSTOMER'                            => 'Vom Kunden angefordert',
    'STRIPE_REFUND_FRAUD'                               => 'Betrug',
    'STRIPE_IS_NOT_STRIPE_ORDER'                        => 'Dies ist keine Stripe Bestellung',
);
