<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    /* SETTINGS */
    'SHOP_MODULE_GROUP_STRIPE_GENERAL'                  => 'Basic configuration',
    'SHOP_MODULE_sStripeMode'                           => 'Mode',
    'SHOP_MODULE_sStripeMode_live'                      => 'Live',
    'SHOP_MODULE_sStripeMode_test'                      => 'Test',
    'SHOP_MODULE_sStripeTestToken'                      => 'Test API Access Token',
    'SHOP_MODULE_sStripeTestPk'                         => 'Test API Publishable Key',
    'SHOP_MODULE_sStripeLiveToken'                      => 'Live API  Access Token',
    'SHOP_MODULE_sStripeLivePk'                         => 'Live API Publishable Key',
    'SHOP_MODULE_sStripeTestKey'                        => 'Test API Private Key',
    'SHOP_MODULE_sStripeLiveKey'                        => 'Live API Private  Key',
    'SHOP_MODULE_blStripeLogTransactionInfo'            => 'Log result of transaction handling',
    'SHOP_MODULE_blStripeRemoveDeactivatedMethods'      => 'Remove deactivated payment types',
    'SHOP_MODULE_blStripeRemoveByBillingCountry'        => 'Remove not supported payment types by billing country',
    'SHOP_MODULE_blStripeRemoveByBasketCurrency'        => 'Remove not supported payment types by basket currency',
    'SHOP_MODULE_GROUP_STRIPE_STATUS_MAPPING'           => 'Status Mapping',
    'SHOP_MODULE_sStripeStatusPending'                  => 'Status Pending',
    'SHOP_MODULE_sStripeStatusProcessing'               => 'Status Processing',
    'SHOP_MODULE_sStripeStatusCancelled'                => 'Status Cancelled',
    'SHOP_MODULE_GROUP_STRIPE_CRONJOBS'                 => 'Cronjobs',
    'SHOP_MODULE_sStripeCronFinishOrdersActive'         => 'Cronjob "Completion of paid but unfinished orders" active',
    'SHOP_MODULE_sStripeCronSecondChanceActive'         => 'Cronjob "Dispatch of payment reminder email" active',
    'SHOP_MODULE_iStripeCronSecondChanceTimeDiff'       => 'Timeframe after which payment reminder email is sent',
    'SHOP_MODULE_sStripeCronOrderShipmentActive'        => 'Cronjob "Transmission of shipping status to Stripe" active',
    'SHOP_MODULE_sStripeCronSecureKey'                  => 'Cronjob secure key',
    'SHOP_MODULE_GROUP_STRIPE_WEBHOOKS'                 => 'Webhooks',
    'SHOP_MODULE_sStripeWebhookEndpoint'                => 'Webhook Endpoint',

    'HELP_SHOP_MODULE_sStripeTestKey'                   => 'Fill in your personal TEST private API key that will be used to set up the webhook endpoint.',
    'HELP_SHOP_MODULE_sStripeLiveKey'                   => 'Fill in your personal LIVE private API key that will be used to set up the webhook endpoint.',
    'HELP_SHOP_MODULE_blStripeLogTransactionInfo'       => 'Log file to be found here: SHOPROOT/log/StripeTransactions.log',
    'HELP_SHOP_MODULE_blStripeRemoveDeactivatedMethods' => 'Removes the payment types from the frontend payment selection which are not activated in the Stripe Dashboard and thus would result in an error.',
    'HELP_SHOP_MODULE_blStripeRemoveByBillingCountry'   => 'Removes the payment types from the frontend payment selection which are not supported for the billing country given by the customer and thus would result in an error.',
    'HELP_SHOP_MODULE_blStripeRemoveByBasketCurrency'   => 'Removes the payment types from the frontend payment selection which are not supported for the basket currency given by the customer and thus would result in an error.',
    'HELP_SHOP_MODULE_sStripeStatusPending'             => 'Set the order status before the customer is redirected to Payment Gateway',
    'HELP_SHOP_MODULE_sStripeStatusProcessing'          => 'Set the order status for Completed Payments',
    'HELP_SHOP_MODULE_sStripeStatusCancelled'           => 'Set the order status for cancelled orders',
    'HELP_SHOP_MODULE_sStripeCronFinishOrdersActive'    => 'This cronjob has the job to finish orders where the customer paid successfully but seemingly didnt return to the shop to complete the order process. The cronjob only finishes orders from the last 24 hours, to not change orders that were probably handled manually.<br><br>For this cronjob to work, in addition to this checkbox you have to ensure that the Stripe cronjob is set up properly. You can find information on how to set up the cronjob in the README.md of this module.',
    'HELP_SHOP_MODULE_sStripeCronSecondChanceActive'    => 'For this cronjob to work, in addition to this checkbox you have to ensure that the Stripe cronjob is set up properly. You can find information on how to set up the cronjob in the README.md of this module.',
    'HELP_SHOP_MODULE_sStripeCronOrderShipmentActive'   => 'This cronjob is only needed if the shipping status in your shop is set by an external service and NOT by the "Ship Now" button. For this cronjob to work, in addition to this checkbox you have to ensure that the Stripe cronjob is set up properly. You can find information on how to set up the cronjob in the README.md of this module.',
    'HELP_SHOP_MODULE_sStripeCronSecureKey'             => 'This option is only needed if you have to call the cronjob via URL instead of the php cli. Configure your secure key here, which you have to add to the cronjob call as the GET parameter "secureKey". Example: https://YOUR-SHOP-URL-HERE/modules/fc/stripe/cron.php?secureKey=YOUR-SECURE-KEY',

    'STRIPE_YES'                                        => 'Yes',
    'STRIPE_NO'                                         => 'No',
    'STRIPE_DAY'                                        => 'day',
    'STRIPE_DAYS'                                       => 'days',
    'STRIPE_IS_STRIPE'                                  => 'This is a Stripe payment type',
    'STRIPE_IS_METHOD_ACTIVATED'                        => 'This payment type is not activated in your Stripe account!',
    'STRIPE_TOKEN_NOT_CONFIGURED'                       => 'Your Stripe access token was not configured yet! Please proceed to onboarding.',
    'STRIPE_KEY_NOT_CONFIGURED'                         => 'Your Stripe private key was not configured yet! Please configure it in the Basic configuration.',
    'STRIPE_DUE_DATE'                                   => 'Due days',
    'STRIPE_BANKTRANSFER_PENDING'                       => 'Status Pending',
    'STRIPE_ORDER_REFUND'                               => 'Stripe',
    'STRIPE_REFUND_SUCCESSFUL'                          => 'Refund was successful.',
    'STRIPE_NO_STRIPE_PAYMENT'                          => 'This order was not payed with Stripe.',
    'STRIPE_REFUND_QUANTITY'                            => 'Refund quantity',
    'STRIPE_REFUND_AMOUNT'                              => 'Refund amount',
    'STRIPE_TYPE_SELECT_LABEL'                          => 'Refund by',
    'STRIPE_QUANTITY'                                   => 'Quantity',
    'STRIPE_NOTICE'                                     => 'Notice',
    'STRIPE_AMOUNT'                                     => 'Amount',
    'STRIPE_HEADER_ORDERED'                             => 'Ordered',
    'STRIPE_HEADER_REFUNDED'                            => 'Refunded',
    'STRIPE_HEADER_SINGLE_PRICE'                        => 'Unitprice',
    'STRIPE_SHIPPINGCOST'                               => "Shipping cost",
    'STRIPE_PAYMENTTYPESURCHARGE'                       => "Payment surcharge",
    'STRIPE_WRAPPING'                                   => "Giftwrapping",
    'STRIPE_GIFTCARD'                                   => "Greeting card",
    'STRIPE_VOUCHER'                                    => 'Voucher',
    'STRIPE_DISCOUNT'                                   => 'Discount',
    'STRIPE_REFUND_SUBMIT'                              => 'Execute refund',
    'STRIPE_FULL_REFUND'                                => 'Full refund',
    'STRIPE_FULL_REFUND_TEXT'                           => 'Execute full refund with the amount of',
    'STRIPE_FULL_REFUND_NOT_AVAILABLE'                  => 'A full refund is not available for this order anymore, there were partial refunds already.',
    'STRIPE_REFUND_DESCRIPTION'                         => 'Refund notice',
    'STRIPE_REFUND_DESCRIPTION_PLACEHOLDER'             => 'optional - max 140 characters',
    'STRIPE_ORDER_NOT_REFUNDABLE'                       => 'This order has been refunded completely already.',
    'STRIPE_REFUND_REMAINING'                           => 'Refund remaining sum',
    'STRIPE_APPLE_PAY_BUTTON_ONLY_LIVE_MODE'            => 'Please note: Payment with the Apple Pay Button is only available in live-mode.',
    'STRIPE_APIKEY_CONNECTED'                           => 'Connection successful',
    'STRIPE_APIKEY_DISCONNECTED'                        => 'Connection not successful',
    'STRIPE_DEACTIVATED'                                => 'Deactivated',
    'STRIPE_CONNECTION_DATA'                            => 'Access your connection data here:',
    'STRIPE_ORDER_PAYMENT_URL'                          => 'Link to payment completion',
    'STRIPE_SEND_SECOND_CHANCE_MAIL'                    => 'Send Second Chance Email',
    'STRIPE_SECOND_CHANCE_MAIL_ALREADY_SENT'            => 'The email has already been sent.',
    'STRIPE_SUBSEQUENT_ORDER_COMPLETION'                => 'Subsequent order completion',
    'STRIPE_PAYMENT_DESCRIPTION'                        => 'Payment description',
    'STRIPE_PAYMENT_DESCRIPTION_HELP'                   => 'This will be shown to your customer on their card or bank statement when possible.<br><br>You can use the following parameters:<br>{orderId}<br>{orderNumber}<br>{storeName}<br>{customer.firstname}<br>{customer.lastname}<br>{customer.company}',
    'STRIPE_MODULE_VERSION_OUTDATED'                    => 'Caution! The current module version is',
    'STRIPE_PAYMENT_LIMITATION'                         => 'Stripe limitation',
    'STRIPE_PAYMENT_LIMITATION_FROM'                    => 'From',
    'STRIPE_PAYMENT_LIMITATION_TO'                      => 'to',
    'STRIPE_PAYMENT_LIMITATION_UNLIMITED'               => 'unlimited',
    'STRIPE_PAYMENT_DETAILS'                            => 'Payment details',
    'STRIPE_PAYMENT_TYPE'                               => 'Payment type',
    'STRIPE_TRANSACTION_ID'                             => 'Stripe Transaction ID',
    'STRIPE_EXTERNAL_TRANSACTION_ID'                    => 'External Transaction ID',
    'STRIPE_ORDER_EXTRA_INFO'                           => 'Additional information',
    'STRIPE_CONNECT_SUCCESS'                            => 'Stripe Onboarding successful.',
    'STRIPE_CONNECT_ERROR'                              => 'An error occurred during Stripe Onboarding.',
    'STRIPE_BTN_TO_ADMIN'                               => 'To Admin Area',
    'STRIPE_CONFIG_WEBHOOK_CREATE'                      => 'Create webhooks',
    'STRIPE_CONFIG_WEBHOOK_FORCE'                       => 'Force refreshing the webhooks',
    'STRIPE_WEBHOOK_SET'                                => 'Webhook Endpoint is configured.',
    'STRIPE_WEBHOOK_MISSING'                            => 'Webhook Endpoint is missing or invalid.',
    'STRIPE_WEBHOOK_CREATE_ERROR'                       => 'The Webhook Endpoint could not be created.',
    'STRIPE_WEBHOOK_CREATE_ERROR_DELETE_FAILED'         => 'The Webhook Endpoint could not be created. Deletion of existing WH Endpoint failed.',
    'STRIPE_REFUND_REASON'                              => 'Refund reason (optional)',
    'STRIPE_PLEASE_SELECT'                              => '-- Please select --',
    'STRIPE_REFUND_DUPLICATE'                           => 'Duplicate',
    'STRIPE_REFUND_CUSTOMER'                            => 'Requested by customer',
    'STRIPE_REFUND_FRAUD'                               => 'Fraud',
    'STRIPE_IS_NOT_STRIPE_ORDER'                        => 'This is not a Stripe order',
);
